version: '3'

services:
  postgres-database:
    container_name: postgres-nlw
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5434:5432"
